### ISSUE TITLE
Allow the queue to manually be flushed on demand

### ISSUE THREAD

**Issue by Andrewangeta** [orlandos-nl/MongoQueue#10]
I'm running into a use case where it'd be extremely helpful to manually "flush the queue" possibly with a timeout. 
Main use case for now is just unit tests. 

I can imagine an API like this.

`try await queue.flush(timeout: 300)`
And this will attempt to pickup and execute all jobs and returns after the queue is empty.
This would supplement/replace the call `try await queue.run/inBackground()` in unit tests. This way we don't have to use this flow 

```swift
   queue.registerTask(MyTask.self, context: app)        
   try await queue.queueTask(Mytask())        
   try queue.runInBackground()
        
   // Sleep to allow queue to pick up the tasks.
   try await Task.sleep(nanoseconds: 5000000000) // 5 seconds
```

But instead we could do this 

```swift
   queue.registerTask(MyTask.self, context: app)        
   try await queue.queueTask(Mytask())        
   try await queue.flush(timeout: 300)
   
   XCTAssertTrue(...)
```

**Comment by Joannis** [comment]
Has been implemented in 1.0
