### ISSUE TITLE
Option to avoid queueing same task twice

### ISSUE THREAD

**Issue by Sherlouk** [orlandos-nl/MongoQueue#12]
It would be nice if there was a way to prevent a task from being queued multiple times, especially if given the exact same context/configuration. This would throw an `alreadyQueued` error when queued.

This would be optional, and off by default to prevent backwards compatibility issues.

**Comment by Sherlouk** [comment]
I'm currently achieving this with my own check against Mongo:

```
let document = try await coll.findOne("category" == Self.category && "metadata.type" == type.rawValue && "status" != "dequeued")
return document != nil
```

If this returns true, then I don't queue another job since one already exists.

**Comment by Joannis** [comment]
@Sherlouk would you mind hopping on our discord so that I can discuss the request a bit better? I don't see how you'd be looking to use this feature.

**Comment by Joannis** [comment]
@Sherlouk would you mind hopping on our discord so that I can discuss the request a bit better? I don't see how you'd be looking to use this feature.
