### ISSUE TITLE
Question: How to Use updateActivity Method in RecurringTask

### ISSUE THREAD

**Issue by david-spaeth** [orlandos-nl/MongoQueue#21]
I have a recurring import task that can take a long time. From reading the code a bit, I understood that the update date is used to intelligently manage resuming the task in case of a crash, and that it's important to regularly update this date during task execution. 

I saw there's the `updateActivity` method, but I'm having trouble figuring out how to call it from my `RecurringTask`.

Could someone please advise on how to correctly utilize the `updateActivity` method ? 

Thank you!

**Comment by Joannis** [comment]
This bit of code already updates `execution.lastUpdate` for you and is called while your job runner is running the task.
https://github.com/orlandos-nl/MongoQueue/blob/83548920d27c3424ed17ad471f5fca5f15ac9189/Sources/MongoQueue/KnownType.swift#L95-L109

**Comment by david-spaeth** [comment]
OK thanks .
 My task can take a long time and I can track its progress. Isn't there a way for me to dynamically extend the lifetime of my task, allowing me to set a reasonable maximum execution time? 
 
I'm trying to solve a scenario that will almost never happen (and it will 😅), i.e. if the server crashes while my task is in running state and it doesn't resume until its expiration date, which can be several hours.

**Comment by Joannis** [comment]
The lifetime is automatically extended, the execution time should've really been `estimatedExecutionTime`

**Comment by david-spaeth** [comment]
Following your response, I just reread the code and the documentation. Things are clearer to me now. Thank you very much for your response and your libraries.
