### ISSUE TITLE
Add support for optionally keeping failed tasks in the queue

### ISSUE THREAD

**Issue by Andrewangeta** [orlandos-nl/MongoQueue#4]
Often at times I find myself wanting to retry a failed task.
While the option to set a maximum retry using the retry api 
```swift
public func onExecutionFailure(failureContext: QueuedTaskFailure<Context>) async throws -> TaskExecutionFailureAction {
     .retry(maxAttempts: 5)
  }
```
Even then if something fails 5 times in this example the task is just deleted with no record of the payload etc. and one would have t hopefully rely on logging to pinpoint the reason for a failure.

A better alternative would be to keep the task in the queue but have it marked as `failed` with a new status or make use of the existing [`suspended` status ](https://github.com/orlandos-nl/MongoQueue/blob/7331a5efdb60f4d5050ff5546c44ae1c3e6340ad/Sources/MongoQueue/MongoQueue.swift#L7)

This gives us the flexibility to run the task locally while debugging to use breakpoints and a debugger to pinpoint the reasons for a failure. This also allows us to potentially build a frontend (queue dashboard 😉) to have insight into tasks failures and even for monitoring queue health etc.

I imagine an API for this could be something like 
```swift
/// configure globally for all tasks
let queue = MongoQueue(collection: mongoDatabase["queue"], keepFailedTasksInQueue: true)

/// or maybe per individual tasks you care to keep
queue.registerTask(PushNotificationTask.self, context: ..., keepFailedTaskInQueue: true)
/// with this approach we can have access to the `KnownType` and make the decision when catching the error after execution.
```

**Comment by Joannis** [comment]
See #5
